### ISSUE TITLE
http://www.bellevue-rodrigues.com gallery images showing other object also

### ISSUE THREAD

**Issue by Owners-United** [PPDesign/MD#15]
please check there must be a double object upload here.
We are showing fenetre sur Mer here only please.

**Comment by oceanic817** [comment]
fixed. sorry, ihad to rebuild the gallery and some other pics were broadcasted. all done

**Comment by Owners-United** [comment]
Well done nice job,

thank you very much guys

grazie mille,

Richi

Von: oceanic817 [mailto:notifications@github.com] 
Gesendet: Dienstag, 12. August 2014 12:18
An: PPDesign/MD
Cc: Owners-United
Betreff: Re: [MD] http://www.bellevue-rodrigues.com gallery images showing other object also (#15)

fixed. sorry, ihad to rebuild the gallery and some other pics were broadcasted. all done
