### ISSUE TITLE
add video to villa mon calme on http://www.rodrigues-villas.com/

### ISSUE THREAD

**Issue by Owners-United** [PPDesign/MD#19]
Salve PP,

can you please upload the new video to Villa MOn Calme on
http://www.rodrigues-villas.com/
same as you did last time for fenetre sur mer.
Here the link to the direct download
https://app.box.com/s/cr59t7zhkuvgsujxblhl
I will forward you the Email from the video guy as well.

Grazie,
Richi

**Comment by pierpablohoney** [comment]
Davide the link is the same at the one of the previous Video except the last part as following:

../Mon_Calme/Mon_Calme.html

Please add the video in the single page of Villa Mon Calme.

**Comment by oceanic817** [comment]
done

**Comment by Owners-United** [comment]
Grazie well done,

please have a look there is 1 image showing twice on

http://www.rodrigues-villas.com/villa-mon-calme/

olease remove the last image with the pool

110_01c_rodrigues_private_villa_to_rent

Grazie,

Richi

Von: oceanic817 [mailto:notifications@github.com] 
Gesendet: Donnerstag, 11. September 2014 00:41
An: PPDesign/MD
Cc: Owners-United
Betreff: Re: [MD] add video to villa mon calme on http://www.rodrigues-villas.com/ (#19)

done

**Comment by oceanic817** [comment]
done
