### ISSUE TITLE
test pp 1

### ISSUE THREAD

**Issue by Owners-United** [PPDesign/MD#3]
can xou please add amap to josephine?

**Comment by pierpablohoney** [comment]
thi is fixed

**Comment by Owners-United** [comment]
yes pp what did you do ther e map is not showing

**Comment by Owners-United** [comment]
here is an image to show 
![11 pp test](https://cloud.githubusercontent.com/assets/8336608/3787662/27fe4786-1a2a-11e4-8906-92f01fc99ba2.JPG)

**Comment by pierpablohoney** [comment]
now i got it and it is fixed
