### ISSUE TITLE
Fenetre sur Mer

### ISSUE THREAD

**Issue by Owners-United** [PPDesign/MD#7]
Single Property page
Object called in MD
Villa Fenetre sur Mer
Domain Name: www.bellevue-rodrigues.com
Webspace /mauritiusdirect
E-Mail : contact@bellevue-rodrigues.com
Video: https://www.dropbox.com/sh/7zq9khc2e0klrgi/AADQ5XZyhkUsfol4rWjQ0PrDa

**Comment by Owners-United** [comment]
Salve PP,
can you please let me know when you can finalize this page?
Please use another layout colour for this one.
www.palmarplage.com 2 object page looks o.k. for us, please correct the url for the moment it is showing http://www.mauritius-direct.com/palmarplage/villa-isabella

Grazie mille,
Richi

**Comment by oceanic817** [comment]
I ll finish fenetre sur mer before tomorrow morning. 
Different color is for palmarplage? Some fabourite colour?

Davide

**Comment by oceanic817** [comment]
ciao richard, www.bellevue-rodrigues.com is online

what do you mean for:
"please correct the url for the moment it is showing http://www.mauritius-direct.com/palmarplage/villa-isabella"

if you refer at the "view calendar" button, i put this url because people can see the availabity of the villa

Pierpaolo will work on video link.

Il giorno 08/ago/2014, alle ore 18:41, Owners-United ha scritto:

> Salve PP,
> can you please let me know when you can finalize this page?
> Please use another layout colour for this one.
> www.palmarplage.com 2 object page looks o.k. for us, please correct the url for the moment it is showing http://www.mauritius-direct.com/palmarplage/villa-isabella
> 
> Grazie mille,
> Richi
> 
> —
> Reply to this email directly or view it on GitHub.

davide
oceanic817@gmail.com

**Comment by Owners-United** [comment]
Yes for palmarplage please,

something elegant around

0a0147

Please try and let me know.

Grazie,

Tichi

Von: oceanic817 [mailto:notifications@github.com] 
Gesendet: Freitag, 8. August 2014 19:02
An: PPDesign/MD
Cc: Owners-United
Betreff: Re: [MD] Fenetre sur Mer (#7)

I ll finish fenetre sur mer before tomorrow morning. 
Different color is for palmarplage? Some fabourite colour? 

Davide

**Comment by oceanic817** [comment]
Yesterday i put orange. If u want i change it

Davide

**Comment by Owners-United** [comment]
Ciao Davide,

va bene grazie

Von: oceanic817 [mailto:notifications@github.com] 
Gesendet: Samstag, 9. August 2014 00:01
An: PPDesign/MD
Cc: Owners-United
Betreff: Re: [MD] Fenetre sur Mer (#7)

ciao richard, www.bellevue-rodrigues.com is online 

what do you mean for: 
"please correct the url for the moment it is showing http://www.mauritius-direct.com/palmarplage/villa-isabella" 

if you refer at the "view calendar" button, i put this url because people can see the availabity of the villa 

Pierpaolo will work on video link. 

Il giorno 08/ago/2014, alle ore 18:41, Owners-United ha scritto: 

> Salve PP, 
> can you please let me know when you can finalize this page? 
> Please use another layout colour for this one. 
> www.palmarplage.com 2 object page looks o.k. for us, please correct the url for the moment it is showing http://www.mauritius-direct.com/palmarplage/villa-isabella 
> 
> Grazie mille, 
> Richi 
> 
> — 
> Reply to this email directly or view it on GitHub. 

davide 
oceanic817@gmail.com

**Comment by Owners-United** [comment]
Didnt see,

yes looks ok. Grazie.

Salve,

Richi

Von: oceanic817 [mailto:notifications@github.com] 
Gesendet: Samstag, 9. August 2014 10:32
An: PPDesign/MD
Cc: Owners-United
Betreff: Re: [MD] Fenetre sur Mer (#7)

Yesterday i put orange. If u want i change it 

Davide

**Comment by Owners-United** [comment]
Gallery not showing

**Comment by oceanic817** [comment]
gallery fixed. video navigation added on homepage.
