### ISSUE TITLE
http://www.mauritius-exclusive.com/

### ISSUE THREAD

**Issue by Owners-United** [PPDesign/MD#9]
page not online

**Comment by Owners-United** [comment]
getting urgent

**Comment by pierpablohoney** [comment]
website back online

**Comment by Owners-United** [comment]
No pp there is another problem puretec did block it again

Von: pierpablohoney [mailto:notifications@github.com] 
Gesendet: Dienstag, 9. September 2014 23:17
An: PPDesign/MD
Cc: Owners-United
Betreff: Re: [MD] http://www.mauritius-exclusive.com/ (#9)

website back online

**Comment by pierpablohoney** [comment]
now working

**Comment by Owners-United** [comment]
Ciao PP,

there must be some conflict with the q-translate.

Some content is showing twice.

Grazie,

Richi

Von: pierpablohoney [mailto:notifications@github.com] 
Gesendet: Mittwoch, 10. September 2014 19:36
An: PPDesign/MD
Cc: Owners-United
Betreff: Re: [MD] http://www.mauritius-exclusive.com/ (#9)

now working
